// <auto-generated />
namespace SimpleBookStoreApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedImageUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedImageUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181123302_AddedImageUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
